name: Verify

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: go/src/github.com/shipwright-io/build
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.x'
        check-latest: true
        cache-dependency-path: go/src/github.com/shipwright-io/triggers
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: go/src/github.com/shipwright-io/triggers
        args: --timeout=10m
